/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package virtickx;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import javax.swing.JRootPane;
/**
 *
 * @author Dell
 */
public class Settings extends javax.swing.JFrame {

    /**
     * Creates new form Settings
     */
    public Settings() {
        setUndecorated(true);  
        getRootPane().setWindowDecorationStyle(JRootPane.NONE);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox();
        jComboBox3 = new javax.swing.JComboBox();
        jComboBox4 = new javax.swing.JComboBox();
        jComboBox5 = new javax.swing.JComboBox();
        jComboBox6 = new javax.swing.JComboBox();
        jComboBox7 = new javax.swing.JComboBox();
        jComboBox8 = new javax.swing.JComboBox();
        jComboBox9 = new javax.swing.JComboBox();
        jPanel1 = new javax.swing.JPanel();
        jCheckBox2 = new javax.swing.JCheckBox();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jSlider1 = new javax.swing.JSlider();
        jLabel13 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jSlider2 = new javax.swing.JSlider();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jComboBox10 = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jComboBox11 = new javax.swing.JComboBox();
        jComboBox12 = new javax.swing.JComboBox();
        jComboBox13 = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel4.setBackground(new java.awt.Color(38, 149, 206));

        jLabel2.setFont(new java.awt.Font("Bookman Old Style", 1, 45)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Dell\\Desktop\\Settings1.png")); // NOI18N
        jLabel2.setText("Controller Settings");

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Dell\\Desktop\\Joystick2.png")); // NOI18N

        jComboBox2.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "NONE", "A", "B", "C", "D", "E", "F", "G", "H", "I", "J", "K", "L", "M", "N", "O", "P", "Q", "R", "S", "T", "U", "V", "W", "X", "Y", "Z", "LEFT BUTTON", "RIGHT BUTTON", "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "DOWN v ", "LEFT <", "RIGHT >", "UP ^", "NUMPAD 0", "NUMPAD 1", "NUMPAD 2", "NUMPAD 3", "NUMPAD 4", "NUMPAD 5", "NUMPAD 6", "NUMPAD 7", "NUMPAD 8", "NUMPAD 9", "ALT", "ASTERIK *", "BACK QUOTE `", "BACKSLASH \\", "BACKSPACE", "CLOSE BRACKET ]", "COMMA ,", "CONTROL", "DELETE", "END", "EQUALS =", "ESCAPE", "HOME", "INSERT", "MINUS -", "OPEN BRACKET [", "PAGE UP", "PAGE DOWN", "PERIOD .", "PLUS +", "QUOTE '", "SHIFT", "SEMICOLON ;", "SLASH /" }));
            jComboBox2.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jComboBox2ActionPerformed(evt);
                }
            });

            jComboBox3.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
            jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "NONE", "A", "B", "C", "D", "E", "F", "G", "H", "I", "J", "K", "L", "M", "N", "O", "P", "Q", "R", "S", "T", "U", "V", "W", "X", "Y", "Z", "LEFT BUTTON", "RIGHT BUTTON", "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "DOWN v ", "LEFT <", "RIGHT >", "UP ^", "NUMPAD 0", "NUMPAD 1", "NUMPAD 2", "NUMPAD 3", "NUMPAD 4", "NUMPAD 5", "NUMPAD 6", "NUMPAD 7", "NUMPAD 8", "NUMPAD 9", "ALT", "ASTERIK *", "BACK QUOTE `", "BACKSLASH \\", "BACKSPACE", "CLOSE BRACKET ]", "COMMA ,", "CONTROL", "DELETE", "END", "EQUALS =", "ESCAPE", "HOME", "INSERT", "MINUS -", "OPEN BRACKET [", "PAGE UP", "PAGE DOWN", "PERIOD .", "PLUS +", "QUOTE '", "SHIFT", "SEMICOLON ;", "SLASH /" }));
                jComboBox3.addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        jComboBox3ActionPerformed(evt);
                    }
                });

                jComboBox4.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
                jComboBox4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "NONE", "A", "B", "C", "D", "E", "F", "G", "H", "I", "J", "K", "L", "M", "N", "O", "P", "Q", "R", "S", "T", "U", "V", "W", "X", "Y", "Z", "LEFT BUTTON", "RIGHT BUTTON", "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "DOWN v ", "LEFT <", "RIGHT >", "UP ^", "NUMPAD 0", "NUMPAD 1", "NUMPAD 2", "NUMPAD 3", "NUMPAD 4", "NUMPAD 5", "NUMPAD 6", "NUMPAD 7", "NUMPAD 8", "NUMPAD 9", "ALT", "ASTERIK *", "BACK QUOTE `", "BACKSLASH \\", "BACKSPACE", "CLOSE BRACKET ]", "COMMA ,", "CONTROL", "DELETE", "END", "EQUALS =", "ESCAPE", "HOME", "INSERT", "MINUS -", "OPEN BRACKET [", "PAGE UP", "PAGE DOWN", "PERIOD .", "PLUS +", "QUOTE '", "SHIFT", "SEMICOLON ;", "SLASH /" }));
                    jComboBox4.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                            jComboBox4ActionPerformed(evt);
                        }
                    });

                    jComboBox5.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
                    jComboBox5.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "NONE", "A", "B", "C", "D", "E", "F", "G", "H", "I", "J", "K", "L", "M", "N", "O", "P", "Q", "R", "S", "T", "U", "V", "W", "X", "Y", "Z", "LEFT BUTTON", "RIGHT BUTTON", "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "DOWN v ", "LEFT <", "RIGHT >", "UP ^", "NUMPAD 0", "NUMPAD 1", "NUMPAD 2", "NUMPAD 3", "NUMPAD 4", "NUMPAD 5", "NUMPAD 6", "NUMPAD 7", "NUMPAD 8", "NUMPAD 9", "ALT", "ASTERIK *", "BACK QUOTE `", "BACKSLASH \\", "BACKSPACE", "CLOSE BRACKET ]", "COMMA ,", "CONTROL", "DELETE", "END", "EQUALS =", "ESCAPE", "HOME", "INSERT", "MINUS -", "OPEN BRACKET [", "PAGE UP", "PAGE DOWN", "PERIOD .", "PLUS +", "QUOTE '", "SHIFT", "SEMICOLON ;", "SLASH /" }));
                        jComboBox5.addActionListener(new java.awt.event.ActionListener() {
                            public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jComboBox5ActionPerformed(evt);
                            }
                        });

                        jComboBox6.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
                        jComboBox6.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "NONE", "A", "B", "C", "D", "E", "F", "G", "H", "I", "J", "K", "L", "M", "N", "O", "P", "Q", "R", "S", "T", "U", "V", "W", "X", "Y", "Z", "LEFT BUTTON", "RIGHT BUTTON", "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "DOWN v ", "LEFT <", "RIGHT >", "UP ^", "NUMPAD 0", "NUMPAD 1", "NUMPAD 2", "NUMPAD 3", "NUMPAD 4", "NUMPAD 5", "NUMPAD 6", "NUMPAD 7", "NUMPAD 8", "NUMPAD 9", "ALT", "ASTERIK *", "BACK QUOTE `", "BACKSLASH \\", "BACKSPACE", "CLOSE BRACKET ]", "COMMA ,", "CONTROL", "DELETE", "END", "EQUALS =", "ESCAPE", "HOME", "INSERT", "MINUS -", "OPEN BRACKET [", "PAGE UP", "PAGE DOWN", "PERIOD .", "PLUS +", "QUOTE '", "SHIFT", "SEMICOLON ;", "SLASH /" }));
                            jComboBox6.addActionListener(new java.awt.event.ActionListener() {
                                public void actionPerformed(java.awt.event.ActionEvent evt) {
                                    jComboBox6ActionPerformed(evt);
                                }
                            });

                            jComboBox7.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
                            jComboBox7.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "NONE", "A", "B", "C", "D", "E", "F", "G", "H", "I", "J", "K", "L", "M", "N", "O", "P", "Q", "R", "S", "T", "U", "V", "W", "X", "Y", "Z", "LEFT BUTTON", "RIGHT BUTTON", "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "DOWN v ", "LEFT <", "RIGHT >", "UP ^", "NUMPAD 0", "NUMPAD 1", "NUMPAD 2", "NUMPAD 3", "NUMPAD 4", "NUMPAD 5", "NUMPAD 6", "NUMPAD 7", "NUMPAD 8", "NUMPAD 9", "ALT", "ASTERIK *", "BACK QUOTE `", "BACKSLASH \\", "BACKSPACE", "CLOSE BRACKET ]", "COMMA ,", "CONTROL", "DELETE", "END", "EQUALS =", "ESCAPE", "HOME", "INSERT", "MINUS -", "OPEN BRACKET [", "PAGE UP", "PAGE DOWN", "PERIOD .", "PLUS +", "QUOTE '", "SHIFT", "SEMICOLON ;", "SLASH /" }));
                                jComboBox7.addActionListener(new java.awt.event.ActionListener() {
                                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                                        jComboBox7ActionPerformed(evt);
                                    }
                                });

                                jComboBox8.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
                                jComboBox8.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "NONE", "A", "B", "C", "D", "E", "F", "G", "H", "I", "J", "K", "L", "M", "N", "O", "P", "Q", "R", "S", "T", "U", "V", "W", "X", "Y", "Z", "LEFT BUTTON", "RIGHT BUTTON", "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "DOWN v ", "LEFT <", "RIGHT >", "UP ^", "NUMPAD 0", "NUMPAD 1", "NUMPAD 2", "NUMPAD 3", "NUMPAD 4", "NUMPAD 5", "NUMPAD 6", "NUMPAD 7", "NUMPAD 8", "NUMPAD 9", "ALT", "ASTERIK *", "BACK QUOTE `", "BACKSLASH \\", "BACKSPACE", "CLOSE BRACKET ]", "COMMA ,", "CONTROL", "DELETE", "END", "EQUALS =", "ESCAPE", "HOME", "INSERT", "MINUS -", "OPEN BRACKET [", "PAGE UP", "PAGE DOWN", "PERIOD .", "PLUS +", "QUOTE '", "SHIFT", "SEMICOLON ;", "SLASH /" }));
                                    jComboBox8.addActionListener(new java.awt.event.ActionListener() {
                                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                            jComboBox8ActionPerformed(evt);
                                        }
                                    });

                                    jComboBox9.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
                                    jComboBox9.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "NONE", "A", "B", "C", "D", "E", "F", "G", "H", "I", "J", "K", "L", "M", "N", "O", "P", "Q", "R", "S", "T", "U", "V", "W", "X", "Y", "Z", "LEFT BUTTON", "RIGHT BUTTON", "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "DOWN v ", "LEFT <", "RIGHT >", "UP ^", "NUMPAD 0", "NUMPAD 1", "NUMPAD 2", "NUMPAD 3", "NUMPAD 4", "NUMPAD 5", "NUMPAD 6", "NUMPAD 7", "NUMPAD 8", "NUMPAD 9", "ALT", "ASTERIK *", "BACK QUOTE `", "BACKSLASH \\", "BACKSPACE", "CLOSE BRACKET ]", "COMMA ,", "CONTROL", "DELETE", "END", "EQUALS =", "ESCAPE", "HOME", "INSERT", "MINUS -", "OPEN BRACKET [", "PAGE UP", "PAGE DOWN", "PERIOD .", "PLUS +", "QUOTE '", "SHIFT", "SEMICOLON ;", "SLASH /" }));
                                        jComboBox9.addActionListener(new java.awt.event.ActionListener() {
                                            public void actionPerformed(java.awt.event.ActionEvent evt) {
                                                jComboBox9ActionPerformed(evt);
                                            }
                                        });

                                        jPanel1.setBackground(new java.awt.Color(38, 149, 206));
                                        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Sensor Settings", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 24), java.awt.Color.white)); // NOI18N

                                        jCheckBox2.setBackground(new java.awt.Color(38, 149, 208));
                                        jCheckBox2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
                                        jCheckBox2.setText("Mouse Required");
                                        jCheckBox2.addActionListener(new java.awt.event.ActionListener() {
                                            public void actionPerformed(java.awt.event.ActionEvent evt) {
                                                jCheckBox2ActionPerformed(evt);
                                            }
                                        });

                                        jPanel2.setBackground(new java.awt.Color(38, 149, 206));

                                        jLabel4.setBackground(new java.awt.Color(38, 149, 206));
                                        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
                                        jLabel4.setText("Mouse Sensitivity");

                                        jSlider1.setBackground(new java.awt.Color(38, 149, 206));
                                        jSlider1.setForeground(new java.awt.Color(255, 255, 255));
                                        jSlider1.setMajorTickSpacing(5);
                                        jSlider1.setMaximum(20);
                                        jSlider1.setMinorTickSpacing(1);
                                        jSlider1.setPaintLabels(true);
                                        jSlider1.setPaintTicks(true);
                                        jSlider1.setValue(0);
                                        jSlider1.addChangeListener(new javax.swing.event.ChangeListener() {
                                            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                                                jSlider1StateChanged(evt);
                                            }
                                        });

                                        jLabel13.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
                                        jLabel13.setText("Along X :");

                                        jLabel12.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
                                        jLabel12.setText("Along Y:");

                                        jSlider2.setBackground(new java.awt.Color(38, 149, 206));
                                        jSlider2.setForeground(new java.awt.Color(255, 255, 255));
                                        jSlider2.setMajorTickSpacing(5);
                                        jSlider2.setMaximum(20);
                                        jSlider2.setMinorTickSpacing(1);
                                        jSlider2.setPaintLabels(true);
                                        jSlider2.setPaintTicks(true);
                                        jSlider2.setValue(0);
                                        jSlider2.addChangeListener(new javax.swing.event.ChangeListener() {
                                            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                                                jSlider2StateChanged(evt);
                                            }
                                        });

                                        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
                                        jPanel2.setLayout(jPanel2Layout);
                                        jPanel2Layout.setHorizontalGroup(
                                            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jSlider1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel13)
                                                    .addComponent(jLabel12)
                                                    .addComponent(jSlider2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addContainerGap(22, Short.MAX_VALUE))
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(jLabel4)
                                                .addGap(0, 0, Short.MAX_VALUE))
                                        );
                                        jPanel2Layout.setVerticalGroup(
                                            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addComponent(jLabel4)
                                                .addGap(30, 30, 30)
                                                .addComponent(jLabel13)
                                                .addGap(18, 18, 18)
                                                .addComponent(jSlider1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jLabel12)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                                                .addComponent(jSlider2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(20, 20, 20))
                                        );

                                        jPanel3.setBackground(new java.awt.Color(38, 149, 208));

                                        jLabel5.setBackground(new java.awt.Color(38, 149, 206));
                                        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
                                        jLabel5.setText("Tilt Left :");

                                        jComboBox10.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
                                        jComboBox10.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "NONE", "A", "B", "C", "D", "E", "F", "G", "H", "I", "J", "K", "L", "M", "N", "O", "P", "Q", "R", "S", "T", "U", "V", "W", "X", "Y", "Z", "LEFT BUTTON", "RIGHT BUTTON", "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "DOWN v ", "LEFT <", "RIGHT >", "UP ^", "NUMPAD 0", "NUMPAD 1", "NUMPAD 2", "NUMPAD 3", "NUMPAD 4", "NUMPAD 5", "NUMPAD 6", "NUMPAD 7", "NUMPAD 8", "NUMPAD 9", "ALT", "ASTERIK *", "BACK QUOTE `", "BACKSLASH \\", "BACKSPACE", "CLOSE BRACKET ]", "COMMA ,", "CONTROL", "DELETE", "END", "EQUALS =", "ESCAPE", "HOME", "INSERT", "MINUS -", "OPEN BRACKET [", "PAGE UP", "PAGE DOWN", "PERIOD .", "PLUS +", "QUOTE '", "SHIFT", "SEMICOLON ;", "SLASH /" }));
                                            jComboBox10.addActionListener(new java.awt.event.ActionListener() {
                                                public void actionPerformed(java.awt.event.ActionEvent evt) {
                                                    jComboBox10ActionPerformed(evt);
                                                }
                                            });

                                            jLabel6.setBackground(new java.awt.Color(38, 149, 206));
                                            jLabel6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
                                            jLabel6.setText("Tilt Right :");

                                            jLabel7.setBackground(new java.awt.Color(38, 149, 206));
                                            jLabel7.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
                                            jLabel7.setText("Tilt Up :");

                                            jLabel8.setBackground(new java.awt.Color(38, 149, 206));
                                            jLabel8.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
                                            jLabel8.setText("Tilt Down :");

                                            jComboBox11.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
                                            jComboBox11.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "NONE", "A", "B", "C", "D", "E", "F", "G", "H", "I", "J", "K", "L", "M", "N", "O", "P", "Q", "R", "S", "T", "U", "V", "W", "X", "Y", "Z", "LEFT BUTTON", "RIGHT BUTTON", "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "DOWN v ", "LEFT <", "RIGHT >", "UP ^", "NUMPAD 0", "NUMPAD 1", "NUMPAD 2", "NUMPAD 3", "NUMPAD 4", "NUMPAD 5", "NUMPAD 6", "NUMPAD 7", "NUMPAD 8", "NUMPAD 9", "ALT", "ASTERIK *", "BACK QUOTE `", "BACKSLASH \\", "BACKSPACE", "CLOSE BRACKET ]", "COMMA ,", "CONTROL", "DELETE", "END", "EQUALS =", "ESCAPE", "HOME", "INSERT", "MINUS -", "OPEN BRACKET [", "PAGE UP", "PAGE DOWN", "PERIOD .", "PLUS +", "QUOTE '", "SHIFT", "SEMICOLON ;", "SLASH /" }));
                                                jComboBox11.addActionListener(new java.awt.event.ActionListener() {
                                                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                                                        jComboBox11ActionPerformed(evt);
                                                    }
                                                });

                                                jComboBox12.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
                                                jComboBox12.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "NONE", "A", "B", "C", "D", "E", "F", "G", "H", "I", "J", "K", "L", "M", "N", "O", "P", "Q", "R", "S", "T", "U", "V", "W", "X", "Y", "Z", "LEFT BUTTON", "RIGHT BUTTON", "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "DOWN v ", "LEFT <", "RIGHT >", "UP ^", "NUMPAD 0", "NUMPAD 1", "NUMPAD 2", "NUMPAD 3", "NUMPAD 4", "NUMPAD 5", "NUMPAD 6", "NUMPAD 7", "NUMPAD 8", "NUMPAD 9", "ALT", "ASTERIK *", "BACK QUOTE `", "BACKSLASH \\", "BACKSPACE", "CLOSE BRACKET ]", "COMMA ,", "CONTROL", "DELETE", "END", "EQUALS =", "ESCAPE", "HOME", "INSERT", "MINUS -", "OPEN BRACKET [", "PAGE UP", "PAGE DOWN", "PERIOD .", "PLUS +", "QUOTE '", "SHIFT", "SEMICOLON ;", "SLASH /" }));
                                                    jComboBox12.addActionListener(new java.awt.event.ActionListener() {
                                                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                                            jComboBox12ActionPerformed(evt);
                                                        }
                                                    });

                                                    jComboBox13.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
                                                    jComboBox13.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "NONE", "A", "B", "C", "D", "E", "F", "G", "H", "I", "J", "K", "L", "M", "N", "O", "P", "Q", "R", "S", "T", "U", "V", "W", "X", "Y", "Z", "LEFT BUTTON", "RIGHT BUTTON", "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "DOWN v ", "LEFT <", "RIGHT >", "UP ^", "NUMPAD 0", "NUMPAD 1", "NUMPAD 2", "NUMPAD 3", "NUMPAD 4", "NUMPAD 5", "NUMPAD 6", "NUMPAD 7", "NUMPAD 8", "NUMPAD 9", "ALT", "ASTERIK *", "BACK QUOTE `", "BACKSLASH \\", "BACKSPACE", "CLOSE BRACKET ]", "COMMA ,", "CONTROL", "DELETE", "END", "EQUALS =", "ESCAPE", "HOME", "INSERT", "MINUS -", "OPEN BRACKET [", "PAGE UP", "PAGE DOWN", "PERIOD .", "PLUS +", "QUOTE '", "SHIFT", "SEMICOLON ;", "SLASH /" }));
                                                        jComboBox13.addActionListener(new java.awt.event.ActionListener() {
                                                            public void actionPerformed(java.awt.event.ActionEvent evt) {
                                                                jComboBox13ActionPerformed(evt);
                                                            }
                                                        });

                                                        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
                                                        jPanel3.setLayout(jPanel3Layout);
                                                        jPanel3Layout.setHorizontalGroup(
                                                            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addGroup(jPanel3Layout.createSequentialGroup()
                                                                .addContainerGap()
                                                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                    .addComponent(jLabel5)
                                                                    .addComponent(jLabel6)
                                                                    .addComponent(jLabel7)
                                                                    .addComponent(jLabel8))
                                                                .addGap(21, 21, 21)
                                                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                    .addComponent(jComboBox11, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                    .addComponent(jComboBox10, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                    .addComponent(jComboBox12, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                    .addComponent(jComboBox13, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                        );
                                                        jPanel3Layout.setVerticalGroup(
                                                            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addGroup(jPanel3Layout.createSequentialGroup()
                                                                .addContainerGap()
                                                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                                    .addComponent(jLabel5)
                                                                    .addComponent(jComboBox10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                                    .addComponent(jLabel6)
                                                                    .addComponent(jComboBox11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                                    .addComponent(jLabel7)
                                                                    .addComponent(jComboBox12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                                    .addComponent(jLabel8)
                                                                    .addComponent(jComboBox13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                        );

                                                        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
                                                        jPanel1.setLayout(jPanel1Layout);
                                                        jPanel1Layout.setHorizontalGroup(
                                                            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                                                        .addContainerGap()
                                                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                            .addComponent(jCheckBox2)
                                                                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                        );
                                                        jPanel1Layout.setVerticalGroup(
                                                            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addContainerGap()
                                                                .addComponent(jCheckBox2)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                        );

                                                        jButton1.setBackground(new java.awt.Color(255, 255, 255));
                                                        jButton1.setFont(new java.awt.Font("Bookman Old Style", 1, 24)); // NOI18N
                                                        jButton1.setForeground(new java.awt.Color(38, 149, 206));
                                                        jButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Dell\\Desktop\\Done3_clipped_rev_1.png")); // NOI18N
                                                        jButton1.setText("  Done");
                                                        jButton1.addActionListener(new java.awt.event.ActionListener() {
                                                            public void actionPerformed(java.awt.event.ActionEvent evt) {
                                                                jButton1ActionPerformed(evt);
                                                            }
                                                        });

                                                        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
                                                        jPanel4.setLayout(jPanel4Layout);
                                                        jPanel4Layout.setHorizontalGroup(
                                                            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addGroup(jPanel4Layout.createSequentialGroup()
                                                                .addGap(10, 10, 10)
                                                                .addComponent(jLabel1)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                                                        .addGap(10, 10, 10)
                                                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                            .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                            .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                            .addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                            .addComponent(jLabel2)
                                                                            .addGroup(jPanel4Layout.createSequentialGroup()
                                                                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 722, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                    .addComponent(jComboBox9, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                    .addComponent(jComboBox8, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                    .addComponent(jComboBox6, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                    .addComponent(jComboBox7, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                                                        .addGap(0, 29, Short.MAX_VALUE))
                                                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                        .addComponent(jButton1)
                                                                        .addGap(45, 45, 45))))
                                                        );
                                                        jPanel4Layout.setVerticalGroup(
                                                            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addGroup(jPanel4Layout.createSequentialGroup()
                                                                .addGap(118, 118, 118)
                                                                .addComponent(jLabel1)
                                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                                                .addContainerGap(72, Short.MAX_VALUE)
                                                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(70, 70, 70))
                                                            .addGroup(jPanel4Layout.createSequentialGroup()
                                                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                                                        .addContainerGap(184, Short.MAX_VALUE)
                                                                        .addComponent(jComboBox8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addGap(49, 49, 49)
                                                                        .addComponent(jComboBox9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addGap(48, 48, 48)
                                                                        .addComponent(jComboBox6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addGap(58, 58, 58)
                                                                        .addComponent(jComboBox7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addGap(91, 91, 91))
                                                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                            .addGroup(jPanel4Layout.createSequentialGroup()
                                                                                .addGap(185, 185, 185)
                                                                                .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addGap(50, 50, 50)
                                                                                .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addGap(46, 46, 46)
                                                                                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addGap(51, 51, 51)
                                                                                .addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                            .addGroup(jPanel4Layout.createSequentialGroup()
                                                                                .addContainerGap()
                                                                                .addComponent(jLabel2)
                                                                                .addGap(55, 55, 55)
                                                                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(45, 45, 45))
                                                        );

                                                        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                                                        getContentPane().setLayout(layout);
                                                        layout.setHorizontalGroup(
                                                            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        );
                                                        layout.setVerticalGroup(
                                                            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        );

                                                        pack();
                                                        setLocationRelativeTo(null);
                                                    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        keypress1[1]=jComboBox2.getSelectedIndex();
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jSlider1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSlider1StateChanged
        if(SensorStatus==0||!MouseRequired)
            jSlider1.setValue(0);
        else
            MouseSensetivityX=jSlider1.getValue();
    }//GEN-LAST:event_jSlider1StateChanged

    private void jCheckBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox2ActionPerformed
        if(SensorStatus==0)
            jCheckBox2.setSelected(false);
        else
        {
            MouseRequired=jCheckBox2.isSelected();
            if(MouseRequired)
            {
                jComboBox10.setSelectedIndex(0);
                jComboBox11.setSelectedIndex(0);
                jComboBox12.setSelectedIndex(0);
                jComboBox13.setSelectedIndex(0);
            }
            else
            {
                jSlider1.setValue(0);
                jSlider2.setValue(0);
            }
        }
    }//GEN-LAST:event_jCheckBox2ActionPerformed

    private void jComboBox10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox10ActionPerformed
        if(SensorStatus==0||(MouseRequired))
            jComboBox10.setSelectedIndex(0);
        else
        {
            keypress4[0]=jComboBox10.getSelectedIndex();
        }
    }//GEN-LAST:event_jComboBox10ActionPerformed

    private void jComboBox11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox11ActionPerformed
        if(SensorStatus==0||(MouseRequired))
            jComboBox11.setSelectedIndex(0);
        else
        {
            keypress4[1]=jComboBox11.getSelectedIndex();
        }
    }//GEN-LAST:event_jComboBox11ActionPerformed

    private void jComboBox12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox12ActionPerformed
        if(SensorStatus==0||MouseRequired)
            jComboBox12.setSelectedIndex(0);
        else
        {
            keypress4[3]=jComboBox12.getSelectedIndex();
        }
    }//GEN-LAST:event_jComboBox12ActionPerformed

    private void jComboBox13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox13ActionPerformed
        if(SensorStatus==0||MouseRequired)
            jComboBox13.setSelectedIndex(0);
        else
        {
            keypress4[2]=jComboBox13.getSelectedIndex();
        }
    }//GEN-LAST:event_jComboBox13ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        ScreenOn=false;
        close();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed
        keypress1[3]=jComboBox3.getSelectedIndex();
        System.out.println(jComboBox3.getSelectedIndex());
    }//GEN-LAST:event_jComboBox3ActionPerformed

    private void jSlider2StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSlider2StateChanged
        if(SensorStatus==0||!MouseRequired)
            jSlider2.setValue(0);
        else
            MouseSensetivityY=jSlider2.getValue();
    }//GEN-LAST:event_jSlider2StateChanged

    private void jComboBox8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox8ActionPerformed
        keypress2[3]=jComboBox8.getSelectedIndex();
    }//GEN-LAST:event_jComboBox8ActionPerformed

    private void jComboBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox4ActionPerformed
        keypress1[0]=jComboBox4.getSelectedIndex();
    }//GEN-LAST:event_jComboBox4ActionPerformed

    private void jComboBox5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox5ActionPerformed
        keypress1[2]=jComboBox5.getSelectedIndex();
    }//GEN-LAST:event_jComboBox5ActionPerformed

    private void jComboBox9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox9ActionPerformed
        keypress2[0]=jComboBox9.getSelectedIndex();
    }//GEN-LAST:event_jComboBox9ActionPerformed

    private void jComboBox6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox6ActionPerformed
        keypress2[1]=jComboBox6.getSelectedIndex();
    }//GEN-LAST:event_jComboBox6ActionPerformed

    private void jComboBox7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox7ActionPerformed
        keypress2[2]=jComboBox7.getSelectedIndex();
    }//GEN-LAST:event_jComboBox7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Settings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Settings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Settings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Settings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Settings().setVisible(true);
            }
        });
    }
    protected int SensorStatus=0,MouseSensetivityX=0,MouseSensetivityY=0;
    protected boolean MouseRequired=false,ScreenOn=true;
    int keypress1[]={-1,-1,-1,-1};
    int keypress2[]={-1,-1,-1,-1};
    int keypress4[]={-1,-1,-1,-1};
    //int i=1;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JComboBox jComboBox10;
    private javax.swing.JComboBox jComboBox11;
    private javax.swing.JComboBox jComboBox12;
    private javax.swing.JComboBox jComboBox13;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JComboBox jComboBox3;
    private javax.swing.JComboBox jComboBox4;
    private javax.swing.JComboBox jComboBox5;
    private javax.swing.JComboBox jComboBox6;
    private javax.swing.JComboBox jComboBox7;
    private javax.swing.JComboBox jComboBox8;
    private javax.swing.JComboBox jComboBox9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSlider jSlider1;
    private javax.swing.JSlider jSlider2;
    // End of variables declaration//GEN-END:variables
    public void close()
    {
        WindowEvent close_window=new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(close_window);
    }
    public void setDefaultState()
    {
        jComboBox3.setSelectedIndex(keypress1[3]);
        jComboBox5.setSelectedIndex(keypress1[2]);
        jComboBox2.setSelectedIndex(keypress1[1]);
        jComboBox4.setSelectedIndex(keypress1[0]);
        jComboBox8.setSelectedIndex(keypress2[3]);
        jComboBox7.setSelectedIndex(keypress2[2]);
        jComboBox6.setSelectedIndex(keypress2[1]);
        jComboBox9.setSelectedIndex(keypress2[0]);
        jComboBox12.setSelectedIndex(keypress4[3]);
        jComboBox13.setSelectedIndex(keypress4[2]);
        jComboBox11.setSelectedIndex(keypress4[1]);
        jComboBox10.setSelectedIndex(keypress4[0]);
        jSlider1.setValue(MouseSensetivityX);
        jSlider2.setValue(MouseSensetivityY);
        if(MouseRequired&&SensorStatus==1)
            jCheckBox2.setSelected(true);
        else
            jCheckBox2.setSelected(false);
    }
}
